//! Real-CLI checks for the terminal output actions: completion scripts, the
//! man page, help/version, and the rejections around them. Every case in this
//! file must exit without starting the daemon or touching daemon inputs, so
//! they are safe to run in any working directory.

use std::process::Command;

fn shbox() -> Command {
    Command::new(env!("CARGO_BIN_EXE_shbox"))
}

fn stdout_of(command: &mut Command) -> (String, Option<i32>) {
    let output = command.output().expect("spawn shbox");
    (
        String::from_utf8(output.stdout).expect("stdout is UTF-8"),
        output.status.code(),
    )
}

#[test]
fn completions_print_a_script_and_exit_successfully() {
    for shell in ["bash", "zsh", "fish", "powershell"] {
        let (stdout, code) = stdout_of(shbox().args(["--completions", shell]));
        assert_eq!(code, Some(0), "{shell}: exit code");
        assert!(
            stdout.contains("@generated by usage"),
            "{shell}: generated marker missing"
        );
        assert!(stdout.contains("shbox"), "{shell}: binary name missing");
    }
}

#[test]
fn unsupported_completion_shell_fails() {
    for shell in ["nu", "elvish", "sh", "pwsh"] {
        let output = shbox()
            .args(["--completions", shell])
            .output()
            .expect("spawn");
        assert_ne!(output.status.code(), Some(0), "{shell} must be rejected");
        assert!(
            !output.stdout.is_empty() || !output.stderr.is_empty(),
            "{shell}"
        );
    }
}

#[test]
fn man_page_prints_roff_and_exits_successfully() {
    let (stdout, code) = stdout_of(shbox().arg("--man"));
    assert_eq!(code, Some(0));
    assert!(
        stdout.contains(".TH SHBOX 1"),
        "man header missing: {stdout}"
    );
    assert!(
        stdout.contains("\\-\\-completions"),
        "completions flag missing from man page"
    );
    assert!(
        stdout.contains("\\-\\-man"),
        "man flag missing from man page"
    );
}

#[test]
fn conflicting_output_actions_fail() {
    let output = shbox()
        .args(["--completions", "zsh", "--man"])
        .output()
        .expect("spawn shbox");
    assert_ne!(output.status.code(), Some(0));
    let stderr = String::from_utf8(output.stderr).expect("stderr is UTF-8");
    assert!(stderr.contains("mutually exclusive"), "{stderr}");
}

#[test]
fn help_and_version_print_and_exit_successfully() {
    for flag in ["--help", "--version"] {
        let (stdout, code) = stdout_of(shbox().arg(flag));
        assert_eq!(code, Some(0), "{flag}");
        assert!(!stdout.is_empty(), "{flag} must print");
    }
    let (help, _) = stdout_of(shbox().arg("--help"));
    assert!(help.contains("--completions"), "help lists --completions");
    assert!(help.contains("--man"), "help lists --man");
    assert!(help.contains("--listen"), "help lists --listen");
    assert!(help.contains("--network"), "help lists --network");
    assert!(help.contains("--log-level"), "help lists --log-level");
    assert!(
        help.contains("--authorized-keys-host-access"),
        "help lists --authorized-keys-host-access"
    );
}

#[test]
fn unknown_flags_fail() {
    let output = shbox().arg("--no-such-flag").output().expect("spawn shbox");
    assert_ne!(output.status.code(), Some(0));
}
